// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CsrfHeaderScopes    = "CsrfHeader.Scopes"
	SessionCookieScopes = "SessionCookie.Scopes"
)

// Defines values for AssistantConversationState.
const (
	AssistantConversationStateAwaitingClarification AssistantConversationState = "awaiting_clarification"
	AssistantConversationStateError                 AssistantConversationState = "error"
	AssistantConversationStateIdle                  AssistantConversationState = "idle"
	AssistantConversationStateRunning               AssistantConversationState = "running"
	AssistantConversationStateStopped               AssistantConversationState = "stopped"
	AssistantConversationStateUnavailable           AssistantConversationState = "unavailable"
)

// Defines values for AssistantMessageRole.
const (
	AssistantMessageRoleAssistant AssistantMessageRole = "assistant"
	AssistantMessageRoleUser      AssistantMessageRole = "user"
)

// Defines values for AssistantMode.
const (
	Edit AssistantMode = "edit"
	Qa   AssistantMode = "qa"
)

// Defines values for BDDKeyword.
const (
	And   BDDKeyword = "and"
	But   BDDKeyword = "but"
	Given BDDKeyword = "given"
	Then  BDDKeyword = "then"
	When  BDDKeyword = "when"
)

// Defines values for ConceptKind.
const (
	Noun ConceptKind = "noun"
	Verb ConceptKind = "verb"
)

// Defines values for DevelopmentStatus.
const (
	DevelopmentStatusBlocked   DevelopmentStatus = "blocked"
	DevelopmentStatusDeveloped DevelopmentStatus = "developed"
	DevelopmentStatusQueued    DevelopmentStatus = "queued"
	DevelopmentStatusRunning   DevelopmentStatus = "running"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Defines values for PageKind.
const (
	Concept  PageKind = "concept"
	Feature  PageKind = "feature"
	Scenario PageKind = "scenario"
)

// Defines values for ReviewBlockerType.
const (
	ReviewBlockerTypeObjection     ReviewBlockerType = "objection"
	ReviewBlockerTypeParentFeature ReviewBlockerType = "parent_feature"
)

// Defines values for ReviewReadiness.
const (
	ReviewReadinessApproved ReviewReadiness = "approved"
	ReviewReadinessBlocked  ReviewReadiness = "blocked"
	ReviewReadinessReady    ReviewReadiness = "ready"
)

// Defines values for RevisionStatus.
const (
	RevisionStatusApproved   RevisionStatus = "approved"
	RevisionStatusDraft      RevisionStatus = "draft"
	RevisionStatusSuperseded RevisionStatus = "superseded"
)

// Defines values for StepRole.
const (
	Action  StepRole = "action"
	Context StepRole = "context"
	Outcome StepRole = "outcome"
)

// APIError defines model for APIError.
type APIError struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// AssistantClarification defines model for AssistantClarification.
type AssistantClarification struct {
	Choices   *[]string     `json:"choices,omitempty"`
	Message   string        `json:"message"`
	Mode      AssistantMode `json:"mode"`
	RequestId string        `json:"requestId"`
}

// AssistantClarificationResponse defines model for AssistantClarificationResponse.
type AssistantClarificationResponse struct {
	Answer string `json:"answer"`
}

// AssistantConversation defines model for AssistantConversation.
type AssistantConversation struct {
	Clarification *AssistantClarification    `json:"clarification,omitempty"`
	CreatedAt     time.Time                  `json:"createdAt"`
	Id            openapi_types.UUID         `json:"id"`
	LastMode      AssistantMode              `json:"lastMode"`
	Messages      []AssistantMessage         `json:"messages"`
	PrimaryMode   AssistantMode              `json:"primaryMode"`
	State         AssistantConversationState `json:"state"`
	Title         string                     `json:"title"`
	UpdatedAt     time.Time                  `json:"updatedAt"`
}

// AssistantConversationState defines model for AssistantConversationState.
type AssistantConversationState string

// AssistantConversationSummary defines model for AssistantConversationSummary.
type AssistantConversationSummary struct {
	CreatedAt   time.Time                  `json:"createdAt"`
	Id          openapi_types.UUID         `json:"id"`
	LastMode    AssistantMode              `json:"lastMode"`
	PrimaryMode AssistantMode              `json:"primaryMode"`
	State       AssistantConversationState `json:"state"`
	Title       string                     `json:"title"`
	UpdatedAt   time.Time                  `json:"updatedAt"`
}

// AssistantDraftReceipt defines model for AssistantDraftReceipt.
type AssistantDraftReceipt struct {
	PageId     openapi_types.UUID `json:"pageId"`
	PageTitle  string             `json:"pageTitle"`
	RevisionId openapi_types.UUID `json:"revisionId"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Citations []Citation              `json:"citations"`
	Content   string                  `json:"content"`
	CreatedAt time.Time               `json:"createdAt"`
	Drafts    []AssistantDraftReceipt `json:"drafts"`
	Id        string                  `json:"id"`
	Mode      AssistantMode           `json:"mode"`
	Role      AssistantMessageRole    `json:"role"`
}

// AssistantMessageRole defines model for AssistantMessage.Role.
type AssistantMessageRole string

// AssistantMode defines model for AssistantMode.
type AssistantMode string

// AssistantProfileStatus defines model for AssistantProfileStatus.
type AssistantProfileStatus struct {
	Configured bool          `json:"configured"`
	Connected  bool          `json:"connected"`
	Message    *string       `json:"message,omitempty"`
	Mode       AssistantMode `json:"mode"`
	Ready      bool          `json:"ready"`
}

// AssistantStatus defines model for AssistantStatus.
type AssistantStatus struct {
	Available bool                   `json:"available"`
	Edit      AssistantProfileStatus `json:"edit"`
	Qa        AssistantProfileStatus `json:"qa"`
}

// AssistantTurnAccepted defines model for AssistantTurnAccepted.
type AssistantTurnAccepted struct {
	Mode   AssistantMode `json:"mode"`
	TurnId string        `json:"turnId"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string                 `json:"action"`
	Actor      *User                  `json:"actor,omitempty"`
	CreatedAt  time.Time              `json:"createdAt"`
	EntityId   *openapi_types.UUID    `json:"entityId,omitempty"`
	EntityType string                 `json:"entityType"`
	Id         openapi_types.UUID     `json:"id"`
	Metadata   map[string]interface{} `json:"metadata"`
}

// BDDKeyword defines model for BDDKeyword.
type BDDKeyword string

// BDDStep defines model for BDDStep.
type BDDStep struct {
	Arguments    []string            `json:"arguments"`
	DefinitionId *openapi_types.UUID `json:"definitionId,omitempty"`
	Expression   *string             `json:"expression,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Keyword      BDDKeyword          `json:"keyword"`
	Position     *int                `json:"position,omitempty"`
	StableId     *openapi_types.UUID `json:"stableId,omitempty"`
	Text         string              `json:"text"`
}

// Citation defines model for Citation.
type Citation struct {
	Draft      bool               `json:"draft"`
	PageId     openapi_types.UUID `json:"pageId"`
	PageTitle  string             `json:"pageTitle"`
	RevisionId openapi_types.UUID `json:"revisionId"`
}

// Comment defines model for Comment.
type Comment struct {
	Author          User                `json:"author"`
	Body            string              `json:"body"`
	CreatedAt       time.Time           `json:"createdAt"`
	Id              openapi_types.UUID  `json:"id"`
	PageId          openapi_types.UUID  `json:"pageId"`
	ParentCommentId *openapi_types.UUID `json:"parentCommentId,omitempty"`
	Replies         []Comment           `json:"replies"`
	RevisionId      openapi_types.UUID  `json:"revisionId"`
}

// CommentRequest defines model for CommentRequest.
type CommentRequest struct {
	Body            string              `json:"body"`
	PageId          openapi_types.UUID  `json:"pageId"`
	ParentCommentId *openapi_types.UUID `json:"parentCommentId,omitempty"`
	RevisionId      openapi_types.UUID  `json:"revisionId"`
}

// ConceptKind defines model for ConceptKind.
type ConceptKind string

// CreateAssistantConversationRequest defines model for CreateAssistantConversationRequest.
type CreateAssistantConversationRequest struct {
	PrimaryMode *AssistantMode `json:"primaryMode,omitempty"`
}

// CreatePageRequest defines model for CreatePageRequest.
type CreatePageRequest struct {
	ConceptKind     *ConceptKind            `json:"conceptKind,omitempty"`
	Content         RevisionContent         `json:"content"`
	InitialScenario *InitialScenarioRequest `json:"initialScenario,omitempty"`
	Kind            PageKind                `json:"kind"`
	ParentId        *openapi_types.UUID     `json:"parentId,omitempty"`
	Slug            string                  `json:"slug"`
}

// DevelopmentStatus defines model for DevelopmentStatus.
type DevelopmentStatus string

// FeatureDevelopmentProgress defines model for FeatureDevelopmentProgress.
type FeatureDevelopmentProgress struct {
	Developed int `json:"developed"`
	Total     int `json:"total"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// InitialScenarioRequest defines model for InitialScenarioRequest.
type InitialScenarioRequest struct {
	Content RevisionContent `json:"content"`
	Slug    string          `json:"slug"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CsrfToken string `json:"csrfToken"`
	User      User   `json:"user"`
}

// Objection defines model for Objection.
type Objection struct {
	Author         User               `json:"author"`
	Body           string             `json:"body"`
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	PageId         openapi_types.UUID `json:"pageId"`
	ResolvedAt     *time.Time         `json:"resolvedAt,omitempty"`
	ResolvedBy     *User              `json:"resolvedBy,omitempty"`
	RevisionId     openapi_types.UUID `json:"revisionId"`
	RevisionNumber int                `json:"revisionNumber"`
}

// ObjectionRequest defines model for ObjectionRequest.
type ObjectionRequest struct {
	Reason string `json:"reason"`
}

// Page defines model for Page.
type Page struct {
	Approved              bool                `json:"approved"`
	ApprovedRevisionId    *openapi_types.UUID `json:"approvedRevisionId,omitempty"`
	ApprovedRevisionTitle *string             `json:"approvedRevisionTitle,omitempty"`
	ConceptKind           *ConceptKind        `json:"conceptKind,omitempty"`
	CreatedAt             time.Time           `json:"createdAt"`
	DraftRevisionTitle    *string             `json:"draftRevisionTitle,omitempty"`
	HasDraft              bool                `json:"hasDraft"`
	Id                    openapi_types.UUID  `json:"id"`
	Kind                  PageKind            `json:"kind"`
	LatestDraftRevisionId *openapi_types.UUID `json:"latestDraftRevisionId,omitempty"`
	ParentId              *openapi_types.UUID `json:"parentId,omitempty"`
	Slug                  string              `json:"slug"`
	Title                 string              `json:"title"`
	UnresolvedObjections  int                 `json:"unresolvedObjections"`
	UpdatedAt             time.Time           `json:"updatedAt"`
}

// PageDetail defines model for PageDetail.
type PageDetail struct {
	ApprovedRevision    *Revision                   `json:"approvedRevision,omitempty"`
	Children            []Page                      `json:"children"`
	Comments            []Comment                   `json:"comments"`
	Development         *ScenarioDevelopment        `json:"development,omitempty"`
	DevelopmentProgress *FeatureDevelopmentProgress `json:"developmentProgress,omitempty"`
	DraftRevision       *Revision                   `json:"draftRevision,omitempty"`
	Objections          []Objection                 `json:"objections"`
	Page                Page                        `json:"page"`
	ReviewStates        []RevisionReviewState       `json:"reviewStates"`
	Revisions           []RevisionSummary           `json:"revisions"`
}

// PageKind defines model for PageKind.
type PageKind string

// PageReference defines model for PageReference.
type PageReference struct {
	Relation        string              `json:"relation"`
	TargetClientKey *string             `json:"targetClientKey,omitempty"`
	TargetPageId    *openapi_types.UUID `json:"targetPageId,omitempty"`
	TargetTitle     *string             `json:"targetTitle,omitempty"`
}

// ReviewBlocker defines model for ReviewBlocker.
type ReviewBlocker struct {
	Author               *User               `json:"author,omitempty"`
	Body                 *string             `json:"body,omitempty"`
	Id                   openapi_types.UUID  `json:"id"`
	RelatedPageId        *openapi_types.UUID `json:"relatedPageId,omitempty"`
	RelatedPageTitle     *string             `json:"relatedPageTitle,omitempty"`
	SourceRevisionId     *openapi_types.UUID `json:"sourceRevisionId,omitempty"`
	SourceRevisionNumber *int                `json:"sourceRevisionNumber,omitempty"`
	Type                 ReviewBlockerType   `json:"type"`
}

// ReviewBlockerType defines model for ReviewBlockerType.
type ReviewBlockerType string

// ReviewReadiness defines model for ReviewReadiness.
type ReviewReadiness string

// Revision defines model for Revision.
type Revision struct {
	ApprovedAt     *time.Time          `json:"approvedAt,omitempty"`
	BaseRevisionId *openapi_types.UUID `json:"baseRevisionId,omitempty"`
	BodyMd         string              `json:"bodyMd"`
	CreatedAt      time.Time           `json:"createdAt"`
	CreatedBy      User                `json:"createdBy"`
	Id             openapi_types.UUID  `json:"id"`
	Number         int                 `json:"number"`
	PageId         openapi_types.UUID  `json:"pageId"`
	References     []PageReference     `json:"references"`
	Status         RevisionStatus      `json:"status"`
	Steps          []BDDStep           `json:"steps"`
	Title          string              `json:"title"`
}

// RevisionContent defines model for RevisionContent.
type RevisionContent struct {
	BodyMd     string          `json:"bodyMd"`
	References []PageReference `json:"references"`
	Steps      []BDDStep       `json:"steps"`
	Title      string          `json:"title"`
}

// RevisionReviewState defines model for RevisionReviewState.
type RevisionReviewState struct {
	Blockers   []ReviewBlocker    `json:"blockers"`
	RevisionId openapi_types.UUID `json:"revisionId"`
	State      ReviewReadiness    `json:"state"`
}

// RevisionStatus defines model for RevisionStatus.
type RevisionStatus string

// RevisionSummary defines model for RevisionSummary.
type RevisionSummary struct {
	ApprovedAt *time.Time         `json:"approvedAt,omitempty"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  User               `json:"createdBy"`
	Id         openapi_types.UUID `json:"id"`
	Number     int                `json:"number"`
	Status     RevisionStatus     `json:"status"`
	Title      string             `json:"title"`
}

// SaveRevisionRequest defines model for SaveRevisionRequest.
type SaveRevisionRequest struct {
	BaseRevisionId openapi_types.UUID `json:"baseRevisionId"`
	Content        RevisionContent    `json:"content"`
}

// ScenarioDevelopment defines model for ScenarioDevelopment.
type ScenarioDevelopment struct {
	Detail     string             `json:"detail"`
	RevisionId openapi_types.UUID `json:"revisionId"`
	Status     DevelopmentStatus  `json:"status"`
	UpdatedAt  time.Time          `json:"updatedAt"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Draft      bool               `json:"draft"`
	Excerpt    string             `json:"excerpt"`
	Page       Page               `json:"page"`
	RevisionId openapi_types.UUID `json:"revisionId"`
	Score      float32            `json:"score"`
}

// StepDefinition defines model for StepDefinition.
type StepDefinition struct {
	Approved   bool               `json:"approved"`
	Expression string             `json:"expression"`
	Id         openapi_types.UUID `json:"id"`
	Role       StepRole           `json:"role"`
	UsageCount int                `json:"usageCount"`
}

// StepRole defines model for StepRole.
type StepRole string

// SubmitAssistantMessageRequest defines model for SubmitAssistantMessageRequest.
type SubmitAssistantMessageRequest struct {
	Content string        `json:"content"`
	Mode    AssistantMode `json:"mode"`
}

// UpdateAssistantConversationSettingsRequest defines model for UpdateAssistantConversationSettingsRequest.
type UpdateAssistantConversationSettingsRequest struct {
	PrimaryMode *AssistantMode `json:"primaryMode,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// ClarificationRequestId defines model for ClarificationRequestId.
type ClarificationRequestId = string

// ConversationId defines model for ConversationId.
type ConversationId = openapi_types.UUID

// PageId defines model for PageId.
type PageId = openapi_types.UUID

// RevisionId defines model for RevisionId.
type RevisionId = openapi_types.UUID

// Error defines model for Error.
type Error = APIError

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// StreamAssistantEventsParams defines parameters for StreamAssistantEvents.
type StreamAssistantEventsParams struct {
	// LastEventID Last received Viki event identifier for short in-memory replay.
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// ListAuditParams defines parameters for ListAudit.
type ListAuditParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrSearchPagesParams defines parameters for ListOrSearchPages.
type ListOrSearchPagesParams struct {
	Q             *string   `form:"q,omitempty" json:"q,omitempty"`
	Kind          *PageKind `form:"kind,omitempty" json:"kind,omitempty"`
	IncludeDrafts *bool     `form:"includeDrafts,omitempty" json:"includeDrafts,omitempty"`
}

// ListStepDefinitionsParams defines parameters for ListStepDefinitions.
type ListStepDefinitionsParams struct {
	Q    *string   `form:"q,omitempty" json:"q,omitempty"`
	Role *StepRole `form:"role,omitempty" json:"role,omitempty"`
}

// CreateAssistantConversationJSONRequestBody defines body for CreateAssistantConversation for application/json ContentType.
type CreateAssistantConversationJSONRequestBody = CreateAssistantConversationRequest

// UpdateAssistantConversationSettingsJSONRequestBody defines body for UpdateAssistantConversationSettings for application/json ContentType.
type UpdateAssistantConversationSettingsJSONRequestBody = UpdateAssistantConversationSettingsRequest

// RespondToAssistantClarificationJSONRequestBody defines body for RespondToAssistantClarification for application/json ContentType.
type RespondToAssistantClarificationJSONRequestBody = AssistantClarificationResponse

// SubmitAssistantMessageJSONRequestBody defines body for SubmitAssistantMessage for application/json ContentType.
type SubmitAssistantMessageJSONRequestBody = SubmitAssistantMessageRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CommentRequest

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = CreatePageRequest

// SaveRevisionJSONRequestBody defines body for SaveRevision for application/json ContentType.
type SaveRevisionJSONRequestBody = SaveRevisionRequest

// RaiseObjectionJSONRequestBody defines body for RaiseObjection for application/json ContentType.
type RaiseObjectionJSONRequestBody = ObjectionRequest
