// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CsrfHeaderScopes    = "CsrfHeader.Scopes"
	SessionCookieScopes = "SessionCookie.Scopes"
)

// Defines values for AssistantChangeOperationOperation.
const (
	Create AssistantChangeOperationOperation = "create"
	Revise AssistantChangeOperationOperation = "revise"
)

// Defines values for AssistantConversationState.
const (
	AssistantConversationStateAwaitingClarification AssistantConversationState = "awaiting_clarification"
	AssistantConversationStateError                 AssistantConversationState = "error"
	AssistantConversationStateIdle                  AssistantConversationState = "idle"
	AssistantConversationStateRunning               AssistantConversationState = "running"
	AssistantConversationStateStopped               AssistantConversationState = "stopped"
	AssistantConversationStateUnavailable           AssistantConversationState = "unavailable"
)

// Defines values for AssistantDraftProposalStatus.
const (
	AwaitingApproval AssistantDraftProposalStatus = "awaiting_approval"
	Discarded        AssistantDraftProposalStatus = "discarded"
	Published        AssistantDraftProposalStatus = "published"
)

// Defines values for AssistantMessageRole.
const (
	AssistantMessageRoleAssistant AssistantMessageRole = "assistant"
	AssistantMessageRoleUser      AssistantMessageRole = "user"
)

// Defines values for AssistantMode.
const (
	Edit AssistantMode = "edit"
	Qa   AssistantMode = "qa"
)

// Defines values for BDDKeyword.
const (
	And   BDDKeyword = "and"
	But   BDDKeyword = "but"
	Given BDDKeyword = "given"
	Then  BDDKeyword = "then"
	When  BDDKeyword = "when"
)

// Defines values for CommentRequestAnchorKind.
const (
	Field CommentRequestAnchorKind = "field"
	Step  CommentRequestAnchorKind = "step"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Defines values for PageKind.
const (
	Primitive   PageKind = "primitive"
	Scenario    PageKind = "scenario"
	Subscenario PageKind = "subscenario"
)

// Defines values for PrimitiveKind.
const (
	Noun PrimitiveKind = "noun"
	Verb PrimitiveKind = "verb"
)

// Defines values for RevisionStatus.
const (
	Accepted   RevisionStatus = "accepted"
	Draft      RevisionStatus = "draft"
	Superseded RevisionStatus = "superseded"
)

// Defines values for VoteValue.
const (
	Approve VoteValue = "approve"
	Reject  VoteValue = "reject"
)

// APIError defines model for APIError.
type APIError struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// AssistantChangeOperation defines model for AssistantChangeOperation.
type AssistantChangeOperation struct {
	BaseRevisionId  *openapi_types.UUID               `json:"baseRevisionId,omitempty"`
	ClientKey       *string                           `json:"clientKey,omitempty"`
	Content         RevisionContent                   `json:"content"`
	Kind            PageKind                          `json:"kind"`
	Operation       AssistantChangeOperationOperation `json:"operation"`
	PageId          *openapi_types.UUID               `json:"pageId,omitempty"`
	ParentClientKey *string                           `json:"parentClientKey,omitempty"`
	ParentId        *openapi_types.UUID               `json:"parentId,omitempty"`
	PrimitiveKind   *PrimitiveKind                    `json:"primitiveKind,omitempty"`
	Slug            string                            `json:"slug"`
}

// AssistantChangeOperationOperation defines model for AssistantChangeOperation.Operation.
type AssistantChangeOperationOperation string

// AssistantClarification defines model for AssistantClarification.
type AssistantClarification struct {
	Choices   *[]string     `json:"choices,omitempty"`
	Message   string        `json:"message"`
	Mode      AssistantMode `json:"mode"`
	RequestId string        `json:"requestId"`
}

// AssistantClarificationResponse defines model for AssistantClarificationResponse.
type AssistantClarificationResponse struct {
	Answer string `json:"answer"`
}

// AssistantConversation defines model for AssistantConversation.
type AssistantConversation struct {
	Clarification *AssistantClarification    `json:"clarification,omitempty"`
	CreatedAt     time.Time                  `json:"createdAt"`
	Id            openapi_types.UUID         `json:"id"`
	LastMode      AssistantMode              `json:"lastMode"`
	Messages      []AssistantMessage         `json:"messages"`
	PrimaryMode   AssistantMode              `json:"primaryMode"`
	State         AssistantConversationState `json:"state"`
	Title         string                     `json:"title"`
	UpdatedAt     time.Time                  `json:"updatedAt"`
}

// AssistantConversationState defines model for AssistantConversationState.
type AssistantConversationState string

// AssistantConversationSummary defines model for AssistantConversationSummary.
type AssistantConversationSummary struct {
	CreatedAt   time.Time                  `json:"createdAt"`
	Id          openapi_types.UUID         `json:"id"`
	LastMode    AssistantMode              `json:"lastMode"`
	PrimaryMode AssistantMode              `json:"primaryMode"`
	State       AssistantConversationState `json:"state"`
	Title       string                     `json:"title"`
	UpdatedAt   time.Time                  `json:"updatedAt"`
}

// AssistantDraftProposal defines model for AssistantDraftProposal.
type AssistantDraftProposal struct {
	ConversationId     openapi_types.UUID           `json:"conversationId"`
	CreatedAt          time.Time                    `json:"createdAt"`
	Id                 openapi_types.UUID           `json:"id"`
	Operations         []AssistantChangeOperation   `json:"operations"`
	PublishedAt        *time.Time                   `json:"publishedAt,omitempty"`
	PublishedRevisions []Revision                   `json:"publishedRevisions"`
	RejectionReason    *string                      `json:"rejectionReason,omitempty"`
	Status             AssistantDraftProposalStatus `json:"status"`
	Summary            string                       `json:"summary"`
	TurnId             openapi_types.UUID           `json:"turnId"`
	UpdatedAt          time.Time                    `json:"updatedAt"`
}

// AssistantDraftProposalStatus defines model for AssistantDraftProposalStatus.
type AssistantDraftProposalStatus string

// AssistantDraftReceipt defines model for AssistantDraftReceipt.
type AssistantDraftReceipt struct {
	PageId     openapi_types.UUID `json:"pageId"`
	PageTitle  string             `json:"pageTitle"`
	RevisionId openapi_types.UUID `json:"revisionId"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Citations []Citation              `json:"citations"`
	Content   string                  `json:"content"`
	CreatedAt time.Time               `json:"createdAt"`
	Drafts    []AssistantDraftReceipt `json:"drafts"`
	Id        string                  `json:"id"`
	Mode      AssistantMode           `json:"mode"`
	Role      AssistantMessageRole    `json:"role"`
}

// AssistantMessageRole defines model for AssistantMessage.Role.
type AssistantMessageRole string

// AssistantMode defines model for AssistantMode.
type AssistantMode string

// AssistantProfileStatus defines model for AssistantProfileStatus.
type AssistantProfileStatus struct {
	Configured bool          `json:"configured"`
	Connected  bool          `json:"connected"`
	Message    *string       `json:"message,omitempty"`
	Mode       AssistantMode `json:"mode"`
	Ready      bool          `json:"ready"`
}

// AssistantStatus defines model for AssistantStatus.
type AssistantStatus struct {
	Available bool                   `json:"available"`
	Edit      AssistantProfileStatus `json:"edit"`
	Qa        AssistantProfileStatus `json:"qa"`
}

// AssistantTurnAccepted defines model for AssistantTurnAccepted.
type AssistantTurnAccepted struct {
	Mode   AssistantMode `json:"mode"`
	TurnId string        `json:"turnId"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action     string                 `json:"action"`
	Actor      *User                  `json:"actor,omitempty"`
	CreatedAt  time.Time              `json:"createdAt"`
	EntityId   *openapi_types.UUID    `json:"entityId,omitempty"`
	EntityType string                 `json:"entityType"`
	Id         openapi_types.UUID     `json:"id"`
	Metadata   map[string]interface{} `json:"metadata"`
}

// BDDKeyword defines model for BDDKeyword.
type BDDKeyword string

// BDDStep defines model for BDDStep.
type BDDStep struct {
	Id       *openapi_types.UUID `json:"id,omitempty"`
	Keyword  BDDKeyword          `json:"keyword"`
	Position *int                `json:"position,omitempty"`
	StableId *openapi_types.UUID `json:"stableId,omitempty"`
	Text     string              `json:"text"`
}

// Citation defines model for Citation.
type Citation struct {
	Draft      bool               `json:"draft"`
	PageId     openapi_types.UUID `json:"pageId"`
	PageTitle  string             `json:"pageTitle"`
	RevisionId openapi_types.UUID `json:"revisionId"`
}

// Comment defines model for Comment.
type Comment struct {
	AnchorId        *string             `json:"anchorId,omitempty"`
	AnchorKind      *string             `json:"anchorKind,omitempty"`
	Author          User                `json:"author"`
	Blocking        bool                `json:"blocking"`
	Body            string              `json:"body"`
	CreatedAt       time.Time           `json:"createdAt"`
	Id              openapi_types.UUID  `json:"id"`
	PageId          openapi_types.UUID  `json:"pageId"`
	ParentCommentId *openapi_types.UUID `json:"parentCommentId,omitempty"`
	Replies         []Comment           `json:"replies"`
	ResolvedAt      *time.Time          `json:"resolvedAt,omitempty"`
	ResolvedBy      *User               `json:"resolvedBy,omitempty"`
	RevisionId      openapi_types.UUID  `json:"revisionId"`
}

// CommentRequest defines model for CommentRequest.
type CommentRequest struct {
	AnchorId        *string                   `json:"anchorId,omitempty"`
	AnchorKind      *CommentRequestAnchorKind `json:"anchorKind,omitempty"`
	Body            string                    `json:"body"`
	PageId          openapi_types.UUID        `json:"pageId"`
	ParentCommentId *openapi_types.UUID       `json:"parentCommentId,omitempty"`
	RevisionId      openapi_types.UUID        `json:"revisionId"`
}

// CommentRequestAnchorKind defines model for CommentRequest.AnchorKind.
type CommentRequestAnchorKind string

// CreateAssistantConversationRequest defines model for CreateAssistantConversationRequest.
type CreateAssistantConversationRequest struct {
	PrimaryMode *AssistantMode `json:"primaryMode,omitempty"`
}

// CreatePageRequest defines model for CreatePageRequest.
type CreatePageRequest struct {
	Content       RevisionContent     `json:"content"`
	Kind          PageKind            `json:"kind"`
	ParentId      *openapi_types.UUID `json:"parentId,omitempty"`
	PrimitiveKind *PrimitiveKind      `json:"primitiveKind,omitempty"`
	Slug          string              `json:"slug"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CsrfToken string `json:"csrfToken"`
	User      User   `json:"user"`
}

// Page defines model for Page.
type Page struct {
	Accepted              bool                `json:"accepted"`
	AcceptedRevisionId    *openapi_types.UUID `json:"acceptedRevisionId,omitempty"`
	CreatedAt             time.Time           `json:"createdAt"`
	HasDraft              bool                `json:"hasDraft"`
	Id                    openapi_types.UUID  `json:"id"`
	Kind                  PageKind            `json:"kind"`
	LatestDraftRevisionId *openapi_types.UUID `json:"latestDraftRevisionId,omitempty"`
	ParentId              *openapi_types.UUID `json:"parentId,omitempty"`
	PrimitiveKind         *PrimitiveKind      `json:"primitiveKind,omitempty"`
	Slug                  string              `json:"slug"`
	Title                 string              `json:"title"`
	UnresolvedRejections  int                 `json:"unresolvedRejections"`
	UpdatedAt             time.Time           `json:"updatedAt"`
}

// PageDetail defines model for PageDetail.
type PageDetail struct {
	AcceptedRevision *Revision         `json:"acceptedRevision,omitempty"`
	Children         []Page            `json:"children"`
	Comments         []Comment         `json:"comments"`
	DraftRevision    *Revision         `json:"draftRevision,omitempty"`
	Page             Page              `json:"page"`
	Revisions        []RevisionSummary `json:"revisions"`
	Votes            []Vote            `json:"votes"`
}

// PageKind defines model for PageKind.
type PageKind string

// PageReference defines model for PageReference.
type PageReference struct {
	Relation        string              `json:"relation"`
	TargetClientKey *string             `json:"targetClientKey,omitempty"`
	TargetPageId    *openapi_types.UUID `json:"targetPageId,omitempty"`
	TargetTitle     *string             `json:"targetTitle,omitempty"`
}

// PrimitiveKind defines model for PrimitiveKind.
type PrimitiveKind string

// RejectDraftProposalInput defines model for RejectDraftProposalInput.
type RejectDraftProposalInput struct {
	Reason string `json:"reason"`
}

// Revision defines model for Revision.
type Revision struct {
	AcceptedAt     *time.Time          `json:"acceptedAt,omitempty"`
	Aliases        []string            `json:"aliases"`
	BaseRevisionId *openapi_types.UUID `json:"baseRevisionId,omitempty"`
	BodyMd         string              `json:"bodyMd"`
	CreatedAt      time.Time           `json:"createdAt"`
	CreatedBy      User                `json:"createdBy"`
	Id             openapi_types.UUID  `json:"id"`
	Number         int                 `json:"number"`
	PageId         openapi_types.UUID  `json:"pageId"`
	References     []PageReference     `json:"references"`
	Status         RevisionStatus      `json:"status"`
	Steps          []BDDStep           `json:"steps"`
	Title          string              `json:"title"`
}

// RevisionContent defines model for RevisionContent.
type RevisionContent struct {
	Aliases    []string        `json:"aliases"`
	BodyMd     string          `json:"bodyMd"`
	References []PageReference `json:"references"`
	Steps      []BDDStep       `json:"steps"`
	Title      string          `json:"title"`
}

// RevisionStatus defines model for RevisionStatus.
type RevisionStatus string

// RevisionSummary defines model for RevisionSummary.
type RevisionSummary struct {
	AcceptedAt *time.Time         `json:"acceptedAt,omitempty"`
	CreatedAt  time.Time          `json:"createdAt"`
	CreatedBy  User               `json:"createdBy"`
	Id         openapi_types.UUID `json:"id"`
	Number     int                `json:"number"`
	Status     RevisionStatus     `json:"status"`
	Title      string             `json:"title"`
}

// SaveRevisionRequest defines model for SaveRevisionRequest.
type SaveRevisionRequest struct {
	BaseRevisionId openapi_types.UUID `json:"baseRevisionId"`
	Content        RevisionContent    `json:"content"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Draft      bool               `json:"draft"`
	Excerpt    string             `json:"excerpt"`
	Page       Page               `json:"page"`
	RevisionId openapi_types.UUID `json:"revisionId"`
	Score      float32            `json:"score"`
}

// SubmitAssistantMessageRequest defines model for SubmitAssistantMessageRequest.
type SubmitAssistantMessageRequest struct {
	Content string        `json:"content"`
	Mode    AssistantMode `json:"mode"`
}

// UpdateAssistantConversationSettingsRequest defines model for UpdateAssistantConversationSettingsRequest.
type UpdateAssistantConversationSettingsRequest struct {
	PrimaryMode *AssistantMode `json:"primaryMode,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
}

// Vote defines model for Vote.
type Vote struct {
	CommentId  *openapi_types.UUID `json:"commentId,omitempty"`
	CreatedAt  time.Time           `json:"createdAt"`
	RevisionId openapi_types.UUID  `json:"revisionId"`
	User       User                `json:"user"`
	Value      VoteValue           `json:"value"`
}

// VoteRequest defines model for VoteRequest.
type VoteRequest struct {
	// Reason Required when value is reject.
	Reason *string   `json:"reason,omitempty"`
	Value  VoteValue `json:"value"`
}

// VoteValue defines model for VoteValue.
type VoteValue string

// ClarificationRequestId defines model for ClarificationRequestId.
type ClarificationRequestId = string

// ConversationId defines model for ConversationId.
type ConversationId = openapi_types.UUID

// PageId defines model for PageId.
type PageId = openapi_types.UUID

// ProposalId defines model for ProposalId.
type ProposalId = openapi_types.UUID

// RevisionId defines model for RevisionId.
type RevisionId = openapi_types.UUID

// Error defines model for Error.
type Error = APIError

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// StreamAssistantEventsParams defines parameters for StreamAssistantEvents.
type StreamAssistantEventsParams struct {
	// LastEventID Last received Viki event identifier for short in-memory replay.
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

// ListAuditParams defines parameters for ListAudit.
type ListAuditParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListOrSearchPagesParams defines parameters for ListOrSearchPages.
type ListOrSearchPagesParams struct {
	Q             *string   `form:"q,omitempty" json:"q,omitempty"`
	Kind          *PageKind `form:"kind,omitempty" json:"kind,omitempty"`
	IncludeDrafts *bool     `form:"includeDrafts,omitempty" json:"includeDrafts,omitempty"`
}

// CreateAssistantConversationJSONRequestBody defines body for CreateAssistantConversation for application/json ContentType.
type CreateAssistantConversationJSONRequestBody = CreateAssistantConversationRequest

// UpdateAssistantConversationSettingsJSONRequestBody defines body for UpdateAssistantConversationSettings for application/json ContentType.
type UpdateAssistantConversationSettingsJSONRequestBody = UpdateAssistantConversationSettingsRequest

// RespondToAssistantClarificationJSONRequestBody defines body for RespondToAssistantClarification for application/json ContentType.
type RespondToAssistantClarificationJSONRequestBody = AssistantClarificationResponse

// SubmitAssistantMessageJSONRequestBody defines body for SubmitAssistantMessage for application/json ContentType.
type SubmitAssistantMessageJSONRequestBody = SubmitAssistantMessageRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CommentRequest

// DiscardDraftProposalJSONRequestBody defines body for DiscardDraftProposal for application/json ContentType.
type DiscardDraftProposalJSONRequestBody = RejectDraftProposalInput

// CreatePageJSONRequestBody defines body for CreatePage for application/json ContentType.
type CreatePageJSONRequestBody = CreatePageRequest

// SaveRevisionJSONRequestBody defines body for SaveRevision for application/json ContentType.
type SaveRevisionJSONRequestBody = SaveRevisionRequest

// SetVoteJSONRequestBody defines body for SetVote for application/json ContentType.
type SetVoteJSONRequestBody = VoteRequest
