/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrSearchPages"];
        put?: never;
        post: operations["createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{pageId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: components["parameters"]["PageId"];
            };
            cookie?: never;
        };
        get: operations["getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{pageId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: components["parameters"]["PageId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["saveRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        get: operations["getRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/revisions/{revisionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/revisions/{revisionId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setVote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{commentId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssistantStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssistantConversations"];
        put?: never;
        post: operations["createAssistantConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get: operations["getAssistantConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAssistantConversationSettings"];
        trace?: never;
    };
    "/api/v1/assistant/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitAssistantMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations/{conversationId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get: operations["streamAssistantEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations/{conversationId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopAssistantTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations/{conversationId}/clarifications/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
                requestId: components["parameters"]["ClarificationRequestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respondToAssistantClarification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDraftProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-proposals/{proposalId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get: operations["getDraftProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-proposals/{proposalId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveDraftProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-proposals/{proposalId}/operations/{operationKey}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
                operationKey: components["parameters"]["OperationKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewDraftProposalOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/draft-proposals/{proposalId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["discardDraftProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HealthStatus: "ok";
        /** @enum {string} */
        PageKind: "concept" | "feature" | "scenario";
        /** @enum {string} */
        ConceptKind: "noun" | "verb";
        /** @enum {string} */
        RevisionStatus: "draft" | "accepted" | "superseded";
        /** @enum {string} */
        VoteValue: "approve" | "reject";
        /** @enum {string} */
        AssistantMode: "qa" | "edit";
        /** @enum {string} */
        AssistantConversationState: "idle" | "running" | "awaiting_clarification" | "stopped" | "error" | "unavailable";
        /** @enum {string} */
        AssistantEventType: "message_delta" | "activity" | "citation" | "draft_created" | "draft_proposed" | "draft_published" | "draft_discarded" | "clarification" | "completed" | "stopped" | "error";
        /** @enum {string} */
        BDDKeyword: "given" | "when" | "then" | "and" | "but";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /** Format: date-time */
            createdAt: string;
        };
        Page: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["PageKind"];
            conceptKind?: components["schemas"]["ConceptKind"];
            /** Format: uuid */
            parentId?: string;
            slug: string;
            title: string;
            /** Format: uuid */
            acceptedRevisionId?: string;
            /** Format: uuid */
            latestDraftRevisionId?: string;
            accepted: boolean;
            hasDraft: boolean;
            unresolvedRejections: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BDDStep: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            stableId?: string;
            position?: number;
            keyword: components["schemas"]["BDDKeyword"];
            text: string;
        };
        PageReference: {
            /** Format: uuid */
            targetPageId?: string;
            targetClientKey?: string;
            targetTitle?: string;
            relation: string;
        };
        RevisionContent: {
            title: string;
            bodyMd: string;
            aliases: string[];
            steps: components["schemas"]["BDDStep"][];
            references: components["schemas"]["PageReference"][];
        };
        Revision: components["schemas"]["RevisionContent"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pageId: string;
            number: number;
            status: components["schemas"]["RevisionStatus"];
            /** Format: uuid */
            baseRevisionId?: string;
            createdBy: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            acceptedAt?: string;
        };
        RevisionSummary: {
            /** Format: uuid */
            id: string;
            number: number;
            status: components["schemas"]["RevisionStatus"];
            title: string;
            createdBy: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            acceptedAt?: string;
        };
        Comment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pageId: string;
            /** Format: uuid */
            revisionId: string;
            /** Format: uuid */
            parentCommentId?: string;
            anchorKind?: string;
            anchorId?: string;
            body: string;
            blocking: boolean;
            author: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            resolvedAt?: string;
            resolvedBy?: components["schemas"]["User"];
            replies: components["schemas"]["Comment"][];
        };
        Vote: {
            /** Format: uuid */
            revisionId: string;
            value: components["schemas"]["VoteValue"];
            user: components["schemas"]["User"];
            /** Format: uuid */
            commentId?: string;
            /** Format: date-time */
            createdAt: string;
        };
        PageDetail: {
            page: components["schemas"]["Page"];
            acceptedRevision?: components["schemas"]["Revision"];
            draftRevision?: components["schemas"]["Revision"];
            revisions: components["schemas"]["RevisionSummary"][];
            comments: components["schemas"]["Comment"][];
            votes: components["schemas"]["Vote"][];
            children: components["schemas"]["Page"][];
        };
        Citation: {
            /** Format: uuid */
            revisionId: string;
            /** Format: uuid */
            pageId: string;
            pageTitle: string;
            draft: boolean;
        };
        AssistantDraftReceipt: {
            /** Format: uuid */
            revisionId: string;
            /** Format: uuid */
            pageId: string;
            pageTitle: string;
        };
        /** @enum {string} */
        AssistantDraftProposalStatus: "awaiting_approval" | "published" | "discarded";
        /** @enum {string} */
        AssistantOperationReviewValue: "approve" | "reject";
        AssistantOperationReview: {
            operationKey: string;
            value: components["schemas"]["AssistantOperationReviewValue"];
            reason?: string;
            /** Format: date-time */
            reviewedAt: string;
        };
        ReviewDraftProposalOperationInput: {
            value: components["schemas"]["AssistantOperationReviewValue"];
            reason?: string;
            /**
             * @description Apply the same decision atomically to child scenarios and newly proposed terms referenced by the selected feature tree.
             * @default false
             */
            cascadeDescendants: boolean;
        };
        RejectDraftProposalInput: {
            reason: string;
        };
        AssistantChangeOperation: {
            /** @enum {string} */
            operation: "create" | "revise";
            clientKey?: string;
            /** Format: uuid */
            pageId?: string;
            /** Format: uuid */
            baseRevisionId?: string;
            kind: components["schemas"]["PageKind"];
            conceptKind?: components["schemas"]["ConceptKind"];
            /** Format: uuid */
            parentId?: string;
            parentClientKey?: string;
            slug: string;
            content: components["schemas"]["RevisionContent"];
        };
        AssistantDraftProposal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            turnId: string;
            summary: string;
            operations: components["schemas"]["AssistantChangeOperation"][];
            operationReviews: components["schemas"]["AssistantOperationReview"][];
            status: components["schemas"]["AssistantDraftProposalStatus"];
            rejectionReason?: string;
            publishedRevisions: components["schemas"]["Revision"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt?: string;
        };
        AssistantMessage: {
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            mode: components["schemas"]["AssistantMode"];
            content: string;
            citations: components["schemas"]["Citation"][];
            drafts: components["schemas"]["AssistantDraftReceipt"][];
            /** Format: date-time */
            createdAt: string;
        };
        AssistantProfileStatus: {
            mode: components["schemas"]["AssistantMode"];
            connected: boolean;
            configured: boolean;
            ready: boolean;
            message?: string;
        };
        AssistantStatus: {
            available: boolean;
            qa: components["schemas"]["AssistantProfileStatus"];
            edit: components["schemas"]["AssistantProfileStatus"];
        };
        AssistantConversationSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            primaryMode: components["schemas"]["AssistantMode"];
            lastMode: components["schemas"]["AssistantMode"];
            state: components["schemas"]["AssistantConversationState"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AssistantClarification: {
            requestId: string;
            mode: components["schemas"]["AssistantMode"];
            message: string;
            choices?: string[];
        };
        AssistantConversation: components["schemas"]["AssistantConversationSummary"] & {
            messages: components["schemas"]["AssistantMessage"][];
            clarification?: components["schemas"]["AssistantClarification"];
        };
        CreateAssistantConversationRequest: {
            primaryMode?: components["schemas"]["AssistantMode"];
        };
        UpdateAssistantConversationSettingsRequest: {
            primaryMode?: components["schemas"]["AssistantMode"];
        };
        SubmitAssistantMessageRequest: {
            content: string;
            mode: components["schemas"]["AssistantMode"];
        };
        AssistantTurnAccepted: {
            turnId: string;
            mode: components["schemas"]["AssistantMode"];
        };
        AssistantClarificationResponse: {
            answer: string;
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            action: string;
            entityType: string;
            /** Format: uuid */
            entityId?: string;
            actor?: components["schemas"]["User"];
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        SearchResult: {
            page: components["schemas"]["Page"];
            /** Format: uuid */
            revisionId: string;
            excerpt: string;
            score: number;
            draft: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["User"];
            csrfToken: string;
        };
        CreatePageRequest: {
            kind: components["schemas"]["PageKind"];
            conceptKind?: components["schemas"]["ConceptKind"];
            /** Format: uuid */
            parentId?: string;
            slug: string;
            content: components["schemas"]["RevisionContent"];
        };
        SaveRevisionRequest: {
            /** Format: uuid */
            baseRevisionId: string;
            content: components["schemas"]["RevisionContent"];
        };
        VoteRequest: {
            value: components["schemas"]["VoteValue"];
            /** @description Required when value is reject. */
            reason?: string;
        };
        CommentRequest: {
            /** Format: uuid */
            pageId: string;
            /** Format: uuid */
            revisionId: string;
            body: string;
            /** Format: uuid */
            parentCommentId?: string;
            /** @enum {string} */
            anchorKind?: "field" | "step";
            anchorId?: string;
        };
        APIError: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: {
        /** @description Request error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Service status. */
        Health: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status: components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    parameters: {
        PageId: string;
        RevisionId: string;
        ConversationId: string;
        ClarificationRequestId: string;
        ProposalId: string;
        OperationKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            503: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated user and CSRF token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listOrSearchPages: {
        parameters: {
            query?: {
                q?: string;
                kind?: components["schemas"]["PageKind"];
                includeDrafts?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page list or ranked search results when q is supplied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pages: components["schemas"]["Page"][];
                    } | {
                        results: components["schemas"]["SearchResult"][];
                    };
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePageRequest"];
            };
        };
        responses: {
            /** @description New page with its initial draft revision. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDetail"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: components["parameters"]["PageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page with accepted and current draft states. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    saveRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pageId: components["parameters"]["PageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRevisionRequest"];
            };
        };
        responses: {
            /** @description New immutable draft revision. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact immutable revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    publishRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page after atomic publication. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDetail"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    setVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: components["parameters"]["RevisionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description Vote attached to the exact revision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vote"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequest"];
            };
        };
        responses: {
            /** @description Thread or reply. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    resolveComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved blocking thread. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only audit events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        events: components["schemas"]["AuditEvent"][];
                    };
                };
            };
        };
    };
    getAssistantStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connectivity and configuration state of both private Hermes profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantStatus"];
                };
            };
        };
    };
    listAssistantConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Body-free Viki bindings enriched from authorized Hermes sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversations: components["schemas"]["AssistantConversationSummary"][];
                    };
                };
            };
        };
    };
    createAssistantConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateAssistantConversationRequest"];
            };
        };
        responses: {
            /** @description New logical conversation binding. Hermes sessions are created lazily. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantConversation"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getAssistantConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unified Q&A/Edit timeline projected from the paired Hermes sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantConversation"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updateAssistantConversationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAssistantConversationSettingsRequest"];
            };
        };
        responses: {
            /** @description Updated body-free conversation settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantConversationSummary"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    submitAssistantMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAssistantMessageRequest"];
            };
        };
        responses: {
            /** @description Hermes accepted the turn. Consume progress from the conversation event stream. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantTurnAccepted"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    streamAssistantEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Last received Viki event identifier for short in-memory replay. */
                "Last-Event-ID"?: string;
            };
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream containing only the documented safe assistant event types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    stopAssistantTurn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Interruption was forwarded to the active Hermes profile. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    respondToAssistantClarification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
                requestId: components["parameters"]["ClarificationRequestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantClarificationResponse"];
            };
        };
        responses: {
            /** @description Clarification answer was forwarded to Hermes. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listDraftProposals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All staged Edit proposals owned by the current user, with pending proposals first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        proposals: components["schemas"]["AssistantDraftProposal"][];
                    };
                };
            };
        };
    };
    getDraftProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Staged Edit proposal owned by the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantDraftProposal"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    approveDraftProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proposal atomically published as accepted revisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantDraftProposal"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    reviewDraftProposalOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
                operationKey: components["parameters"]["OperationKey"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDraftProposalOperationInput"];
            };
        };
        responses: {
            /** @description The operation review was saved. The approved subset is atomically published after every operation has been reviewed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantDraftProposal"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    discardDraftProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposalId: components["parameters"]["ProposalId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectDraftProposalInput"];
            };
        };
        responses: {
            /** @description Proposal rejected with a recorded reason and without creating wiki records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantDraftProposal"];
                };
            };
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
}
